### PR TITLE
Update util.py

### PR DESCRIPTION
**Pull request by ThomasKiljanczykDev**
Fixed generate_deterministic_seeds function

### CODE REVIEW

**Comment by mihahauke** [comment]
Does it cause any problems anywhere? np.iinfo(_np.uint32).max seems to be the highest accepted value.

**Comment by ThomasKiljanczykDev** [comment]
It caused numbers to be out of range some place higher in the traceback hierarchy. I don't remember the exact function.

**Comment by ThomasKiljanczykDev** [comment]
The problem occurs in lab3 when running `test_locally` function. I think that a better solution would be to parametrize seed type. Should I change my fix?

**Comment by ThomasKiljanczykDev** [comment]
Done

**Pull request merged**
